нерелевантный: [нерелевантный, "#ffffff"]
# pie model
LOC: [локация, "#ffffff"]
PER: [персона, "#ffffff"]
ORG: [организация, "#ffffff"]
PHONE_NUMBER: ["номер телефона", "#ffffff"]
BANK_CARD_NUMBER: ["номер карты банка", "#ffffff"]
EMAIL: ["эл. почта", "#ffffff"]
TELEGRAM: ["телеграм", "#ffffff"]
VK: ["вк", "#ffffff"]
# antisui model
"защитные факторы/выражение любви": ["защитные факторы/выражение любви", "#ffffff"]                                                                      
"защитные факторы/выражение счастья, радости, удовлетворенности": ["защитные факторы/выражение счастья, радости, удовлетворенности", "#ffffff"] 
"защитные факторы/желание любви и отношений": ["защитные факторы/желание любви и отношений", "#ffffff"]            
"защитные факторы/наличие позитивных социальных связей": ["защитные факторы/наличие позитивных социальных связей", "#ffffff"]
"защитные факторы/наличие целей, планов на будущее, любимого дела": ["защитные факторы/наличие целей, планов на будущее, любимого дела", "#ffffff"]
"защитные факторы/позитивная самооценка": ["защитные факторы/позитивная самооценка", "#ffffff"]
"защитные факторы/позитивные установки и поиск счастья и радости": ["защитные факторы/позитивные установки и поиск счастья и радости", "#ffffff"]
"защитные факторы/поиск помощи": ["защитные факторы/поиск помощи", "#ffffff"]
"пресуицидальный сигнал": ["нерелевантный", "#ffffff"]
# presuisidal signal
"деструктивное поведение/алкоголь и наркотики": ["деструктивное поведение/алкоголь и наркотики", "#ffffff"]
"деструктивное поведение/самоповреждение": ["деструктивное поведение/самоповреждение", "#ffffff"]
"другое": ["другое", "#ffffff"]
"защитные факторы": ["нерелевантный", "#ffffff"]
"клинические проявления": ["клинические проявления", "#ffffff"]
"клинические проявления/депрессия": ["клинические проявления/депрессия", "#ffffff"]
"клинические проявления/плач, истерики": ["клинические проявления/плач, истерики", "#ffffff"]
"клинические проявления/попытка суицида в прошлом": ["клинические проявления/попытка суицида в прошлом", "#ffffff"]
"нерелевантный": ["нерелевантный", "#ffffff"]
"проблемы в семье": ["проблемы в семье", "#ffffff"]
"проблемы во внешнем мире/несчастная любовь, проблемы с друзьями, сложности построения отношений и чувства/одиночество, непонимание, изоляция, брошенность": ["проблемы во внешнем мире/несчастная любовь, проблемы с друзьями, сложности построения отношений и чувства/одиночество, непонимание, изоляция, брошенность", "#ffffff"]
"смерть/мысли о смерти и намерения самоубийства": ["смерть/мысли о смерти и намерения самоубийства", "#ffffff"]
"смерть/смерть, несчастный случай или суицид близких": ["смерть/смерть, несчастный случай или суицид близких", "#ffffff"]
"чувства": ["чувства", "#ffffff"]
"физическое и сексуализированное насилие, травля": ["Физическое и сексуализированное насилие, травля", "#ffffff"]
